services:
  neodash:
    image: neo4jlabs/neodash:2.4.9
    ports:
      - "5005:5005"
    environment:
      - NEODASH_STANDALONE=false
      - NEODASH_EDIT_MODE=true
      - NEODASH_READ_ONLY=false
      - NEODASH_SSO_ENABLED=false
      - NEODASH_BOLT_URL=bolt://192.168.1.200:7687
      - NEODASH_NEO4J_USER=neo4j
      - NEODASH_NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - google_flights_master_default
    restart: unless-stopped

networks:
  google_flights_master_default:
    external: true
