services:
  neodash:
    image: neo4jlabs/neodash:latest
    container_name: neodash
    ports:
      - "5005:5005"
    environment:
      - ssoEnabled=false
      - standalone=false
      - NEODASH_EDIT_MODE=true
    networks:
      - google_flights_master_default
    restart: unless-stopped

networks:
  google_flights_master_default:
    external: true
